
# Load the data
data_time <- suppressWarnings(DBI::dbGetQuery(con,
                                              "SELECT difficulty,
                                                      response_in_milliseconds,
                                                      new_user_id, score
                                               FROM log_records_1"))

data_users <- suppressWarnings(DBI::dbGetQuery(con,
                                               "SELECT id, gender, grade
                                            FROM users"))

# Rename the id column from the data_users data frame
data_users <- data_users %>%
  rename(new_user_id = id)


getmode <- function(v) { 
  uniqv <- unique(v) 
  uniqv[which.max(tabulate(match(v, uniqv)))]
  }

# Get relative number 
data_all_relative <- data_time %>%
  left_join(data_users) %>%
  group_by(new_user_id) %>%
  mutate(difficulty_summarized = getmode(difficulty),
            response_time_summarized = mean(response_in_milliseconds) / 1000) %>% 
  group_by(grade) %>% 
  count(difficulty_summarized) 
colnames(data_all_relative) <- c('Grade', 'Difficulty', 'Proportion')

# Get total number 
data_all_total <- data_time %>%
  left_join(data_users) %>%
  group_by(new_user_id) %>%
  mutate(difficulty_summarized = getmode(difficulty),
            response_time_summarized = mean(response_in_milliseconds) / 1000) %>% 
  group_by(grade) %>% 
  count() 
colnames(data_all_total) <- c('Grade', 'Total')

# put them in a dataframe
new <- right_join(data_all_total, data_all_relative)

# compute proportion
new %>% 
  mutate(actual_prop = proportion / total)
ncol(new)
new[,5] <- new[,4] / new[,2]
colnames(new) <- c('Grade', 'Total', 'Difficulty','Relative', 'Proportion')

# make the new plot
plot_new <- new %>% 
  ggplot(aes(y = Proportion, x = factor(Grade), fill =factor(Difficulty))) +
  geom_col() + theme_minimal() +
  labs(x = "Grade", y = "Proportion of Chosen Difficulty", fill = "Chosen Difficulty")

plot(plot_new)
ggplotly(plot_new)
